general:
  bg: 0x000000

  tab_bar:
    height: 20
    active_bg: 0x00a3cc
    inactive_bg: 0x262626
    active_text: 0xffffff
    inactive_text: 0xa3a3a3

  bottom_bar:
    height: 20
    active_bg: 0x00a3cc
    inactive_bg: 0xf2f2f2
    active_text: 0xffffff
    inactive_text: 0xc3c3c3

keybindings:
  modifier: "mod1"

  keys:
    - key: "enter"
      action: "exec"
      command: "kitty"

    - key: "q"
      action: "close_focused"

    - key: "shift+e"
      action: "quit"

    - key: "left"
      action: "focus_left"

    - key: "right"
      action: "focus_right"

    - key: "shift+left"
      action: "move_left"

    - key: "shift+right"
      action: "move_right"

    - key: "d"
      action: "exec"
      command: "dmenu_run"
