general:
  bg: 0x000000

  tab_bar:
    height: 20
    active_bg: 0x00a3cc
    inactive_bg: 0x262626
    active_text: 0xffffff
    inactive_text: 0xa3a3a3

  bottom_bar:
    height: 20
    active_bg: 0x00a3cc
    inactive_bg: 0x262626
    active_text: 0xffffff
    inactive_text: 0xa3a3a3

keybindings:
  modifier: "mod1"

  keys:
    - key: "enter"
      action: "exec"
      command: "kitty"

    - key: "q"
      action: "close_focused"

    - key: "shift+e"
      action: "quit"

    - key: "left"
      action: "focus_left"

    - key: "right"
      action: "focus_right"

    - key: "shift+left"
      action: "move_left"

    - key: "shift+right"
      action: "move_right"

    - key: "d"
      action: "exec"
      command: "dmenu_run"

    - key: "1"
      action: "focus_workspace"
      args: "1"

    - key: "2"
      action: "focus_workspace"
      args: "2"

    - key: "3"
      action: "focus_workspace"
      args: "3"

    - key: "4"
      action: "focus_workspace"
      args: "4"

    - key: "5"
      action: "focus_workspace"
      args: "5"

    - key: "6"
      action: "focus_workspace"
      args: "6"

    - key: "7"
      action: "focus_workspace"
      args: "7"

    - key: "8"
      action: "focus_workspace"
      args: "8"

    - key: "9"
      action: "focus_workspace"
      args: "9"

    - key: "0"
      action: "focus_workspace"
      args: "10"
